/hpc2hdd/home/zli755/BASE/conda/envs/reft/bin/deepspeed:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').require('deepspeed==0.14.1+b00902b')
[2024-03-25 16:19:51,912] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-03-25 16:19:52,606] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[93m [WARNING] [0m async_io requires the dev libaio .so object and headers but these were not found.
[93m [WARNING] [0m async_io: please install the libaio-dev package with apt
[93m [WARNING] [0m If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
[93m [WARNING] [0m Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
[93m [WARNING] [0m sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.2
[93m [WARNING] [0m using untested triton version (2.2.0), only 1.0.0 is known to be compatible
[2024-03-25 16:19:57,398] [ERROR] [runner.py:235:_parse_hostfile] Bad hostfile text: ['gpu1-23\n', 'gpu1-23\n', 'gpu1-23\n', 'gpu1-23\n', 'gpu1-23\n', 'gpu1-23\n', 'gpu1-23\n', 'gpu1-23\n', 'gpu1-23\n', 'gpu1-23\n', 'gpu1-23\n', 'gpu1-23\n', 'gpu1-23\n', 'gpu1-23\n', 'gpu1-23\n', 'gpu1-23\n', 'gpu1-23\n', 'gpu1-23\n', 'gpu1-23\n', 'gpu1-23\n', 'gpu1-23\n', 'gpu1-23\n', 'gpu1-23\n', 'gpu1-23\n', 'gpu1-23\n', 'gpu1-23\n', 'gpu1-23\n', 'gpu1-23\n', 'gpu1-23\n', 'gpu1-23\n', 'gpu1-23\n', 'gpu1-23\n', 'gpu1-24\n', 'gpu1-24\n', 'gpu1-24\n', 'gpu1-24\n', 'gpu1-24\n', 'gpu1-24\n', 'gpu1-24\n', 'gpu1-24\n', 'gpu1-24\n', 'gpu1-24\n', 'gpu1-24\n', 'gpu1-24\n', 'gpu1-24\n', 'gpu1-24\n', 'gpu1-24\n', 'gpu1-24\n', 'gpu1-24\n', 'gpu1-24\n', 'gpu1-24\n', 'gpu1-24\n', 'gpu1-24\n', 'gpu1-24\n', 'gpu1-24\n', 'gpu1-24\n', 'gpu1-24\n', 'gpu1-24\n', 'gpu1-24\n', 'gpu1-24\n', 'gpu1-24\n', 'gpu1-24\n', 'gpu1-24\n', 'gpu1-24\n']
Traceback (most recent call last):
  File "/hpc2hdd/home/zli755/BASE/conda/envs/reft/bin/deepspeed", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/hpc2hdd/home/zli755/xueze/reft_ds/DeepSpeed/bin/deepspeed", line 6, in <module>
    main()
  File "/hpc2hdd/home/zli755/xueze/reft_ds/DeepSpeed/deepspeed/launcher/runner.py", line 394, in main
    resource_pool = fetch_hostfile(args.hostfile)
  File "/hpc2hdd/home/zli755/xueze/reft_ds/DeepSpeed/deepspeed/launcher/runner.py", line 210, in fetch_hostfile
    return _parse_hostfile(hostfile_text)
  File "/hpc2hdd/home/zli755/xueze/reft_ds/DeepSpeed/deepspeed/launcher/runner.py", line 236, in _parse_hostfile
    raise ValueError(f"Hostfile contains a bad entry: {line}, unable to proceed with launching")
ValueError: Hostfile contains a bad entry: gpu1-23, unable to proceed with launching
